services:

  app:
    depends_on:
       - db
    build: .
    #image: tomcat:latest
    #container_name: tomcat
    ports:
      - "8089:8085"
    restart: always
    networks:
      - spring-mysql
    #environment:
    #  - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kparun
    #  - SPRING_DATASOURCE_USERNAME=kparun
    #  - SPRING_DATASOURCE_PASSWORD=kparun
    #volumes:
    #  - ./target/ashwin-web.war:/usr/local/tomcat/webapps/ashwin-web.war
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.27
    #command: '--default-authentication-plugin=mysql_native_password'
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=learner_db
      - MYSQL_USER=learner
      - MYSQL_PASSWORD=learner123
    networks:
      - spring-mysql  
    ports:
      - "3306:3306"  
volumes:
  db_data:
networks:
  spring-mysql: